name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        lua_version:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: xpol/setup-lua@v0.3
        with:
          lua-version: ${{ matrix.lua_version }}
      - uses: leafo/gh-actions-luarocks@v4
      - name: install package
        run: luarocks make
